# Generated by Django 3.1.4 on 2021-02-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_infolist_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='infolist',
            name='mainphoto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
