# Generated by Django 3.1.4 on 2021-02-23 01:36

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_wirte'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wirte',
        ),
        migrations.AlterField(
            model_name='infolist',
            name='mainphoto',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
