# Generated by Django 3.1.4 on 2021-02-23 01:38

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210223_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infolist',
            name='information',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=500),
        ),
    ]
