# Generated by Django 3.1.4 on 2021-02-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210223_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infolist',
            name='information',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='infolist',
            name='mainphoto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
