# Generated by Django 3.1.4 on 2021-02-23 05:19

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210223_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infolist',
            name='mainphoto',
        ),
        migrations.AlterField(
            model_name='infolist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='infolist',
            name='information',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infolist',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
