# Generated by Django 3.1.4 on 2021-02-26 01:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210223_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infolist',
            name='information',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
