# Generated by Django 3.1.4 on 2021-02-26 04:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210226_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infolist',
            name='information',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
